import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'es' | 'en' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, variables?: Record<string, string>) => string;
}

const translations: Record<Language, Record<string, string>> = {
  es: {
    // Nav & Common
    'nav.home': 'Inicio',
    'nav.back_to_home': 'Ir al Inicio',
    
    // Hero
    'hero.title1': 'Catálogo',
    'hero.title2': 'Humano',
    'hero.job': 'Estratega, gestor cultural y arquitecto de experiencias.',
    'hero.desc': 'Bienvenido a mi red neuronal: un espacio interactivo donde la música, el código, y el pensamiento crítico colisionan para hackear la monotonía de la realidad.',
    'hero.inventory': 'Inventario',
    'hero.services': 'Servicios (Stats)',
    'hero.years': 'Años',
    
    // Home / Oracle Banner
    'home.testerTitle': 'Beta Tester Interactivo',
    'home.oracleTitle1': 'Oráculo de ',
    'home.oracleTitle2': 'Producción',
    'home.oracleDesc': 'Pon a prueba la viabilidad de tu idea (y mi paciencia) con el generador irónico de proyectos.',
    'home.rollDice': 'Tirar los dados',

    // Ecosystem
    'eco.label': '01 // Ecosistema',
    'eco.title': '01 // Ecosistema',
    'eco.multiverse': 'Multiverso',
    'eco.creative': '—Creativo',
    'eco.desc': 'Cada proyecto es una sinapsis. Un archivo abierto donde cruzo disciplinas para generar cortocircuitos en el pensamiento lineal y esquivar al algoritmo.',
    'eco.cat1': 'Contenido',
    'eco.proj1.desc': 'Espacio dedicado a la creación diaria de contenido cultural y filosófico. Reflexiones sobre la vida que no piden permiso.',
    'eco.proj1.link': 'Explorar Contenido',
    'eco.cat2': 'Blog & Pensamiento',
    'eco.proj2.desc': 'Mi blog personal. Pensamientos extendidos, la vida como RPG, el alma como flujo y ensayos misceláneos sobre el cansancio y el arte.',
    'eco.proj2.link': 'Leer Blog',
    'eco.cat3': 'Música',
    'eco.proj3.desc': 'Integración sonora experiencial. Composiciones que exploran los vínculos, la soledad y la vida en una época descartable.',
    'eco.proj3.link': 'Escuchar en Spotify',
    'eco.cat4': 'Arcade & Game Design',
    'eco.proj4.desc': 'Diseño y mecánicas jugables enfocadas en repensar el \'Dungeon Master\' algorítmico y político. Pong de debate y más.',
    'eco.proj4.link': 'Insert Coin',
    'eco.cat5': 'Mockup Interactivo',
    'eco.proj5.title': 'Una idea para tu evento',
    'eco.proj5.desc': 'La gamificación retiene atención donde el marketing tradicional falla. Prototipo hiper-casual asíncrono para festivales masivos. Convierte el engagement digital en compras (tickets o merch).',
    'eco.proj5.link': 'Juega la Maqueta',

    // Services
    'serv.title': '02 // Inventario de Habilidades',
    'serv.tree': 'Árbol de',
    'serv.skills': 'Skills',
    'serv.desc': 'El backend de mi ecosistema. Herramientas de despliegue táctico donde transfiero la teoría abstracta a resultados operativos y tangibles.',
    'serv.s1.title': 'Estrategia y Megaproducción',
    'serv.s1.desc': 'Traducir visión en logística impecable. De albergar exposiciones internacionales para gobiernos locales e IP, y dirigir subastas de arte de alto impacto social, hasta levantar festivales masivos desde la conceptualización de la idea hasta el evento.',
    'serv.s2.title': 'Política Cultural & Impacto Social',
    'serv.s2.desc': 'Especialista en reactivación comunitaria. He diseñado programas socioculturales (STEAM) tejiendo alianzas globales y locales, logrando resultados tangibles en el territorio a partir de un pensamiento táctico.',
    'serv.s3.title': 'Pensamiento, Narrativa & Oratoria',
    'serv.s3.desc': 'Maestría en Gestión Cultural, Filosofía por la BUAP y Vanguardias en la U. de Salamanca. Diseño discursos, guiones y textos institucionales o literarios que capturan la atención respetando la inteligencia del lector.',
    'serv.s4.title': 'Código, Interfaz y Subversión Web',
    'serv.s4.desc': 'El software es la infraestructura del presente. Construyo ecosistemas web a medida y mecánicas gamificadas para instituciones o creadores que buscan formatos distintos a la plantilla corporativa.',

    // Manifesto
    'mani.title': '03 // Manifiesto',
    'mani.h3': 'Sísifo,',
    'mani.h3.sub': 'pero con un HUD customizado.',
    'mani.quote': '"Soy un filósofo que aprendió a cuadrar presupuestos en Excel, o un productor infiltrado en la academia."',
    'mani.p1': 'Mi bitácora no es una línea recta, es un mapa de colisiones. Pasé por Filosofía en la BUAP, Vanguardias Estéticas en la Universidad de Salamanca (cruzando Madrid) y culminé con una Maestría en Gestión Cultural. Opero desde MX no sólo para observar, sino para detonar intelecto y energía creativa a escala masiva.',
    'mani.p2_1': 'En mi red convergen agendas interinstitucionales con decenas de embajadas, subastas de impacto social y estrategias de inversión privada. He llevado estas visiones del papel al músculo operativo: coordinando ',
    'mani.p2_2': 'más de 600 eventos',
    'mani.p2_3': ', logrando ',
    'mani.p2_4': '+500,000 impactos directos',
    'mani.p2_5': ' y extendiendo estos ecosistemas a ',
    'mani.p2_6': '10 países',
    'mani.p2_7': '.',
    'mani.p3': 'Conozco de primera mano la sobreestimulación contemporánea; por eso creo mis propias salidas de emergencia. Programar una plataforma interactiva o diseñar un macro-festival exige la misma precisión técnica: ordenar el caos e inyectar sentido humano justo allí donde el algoritmo exige ruido.',
    'mani.box1.title': 'Input Neuronal',
    'mani.box1.desc': 'Filosofía / Vanguardias / Diseño',
    'mani.box2.title': 'Procesamiento',
    'mani.box2.desc': '+600 Eventos / Gestión Dinámica',
    'mani.box3.title': 'Output Desplegado',
    'mani.box3.desc': '+500k Impactos en 10 Países',
    
    // Footer Extra
    'footer.location': 'Puebla, México',
    'footer.form.body.name': 'Nombre',
    'footer.form.body.email': 'Email',
    'footer.form.body.topic': 'Motivo',
    'footer.form.body.msg': 'Mensaje',

    // Ecosystem Extra
    'eco.proj4.title': 'Arcade: Parodias 8-bit',

    // Generator Extra
    'orc.default_name': 'Proyectazo',

    // Music Player
    'music.label': 'Música del sitio',
    'music.desc': 'Escucha <b>{{title}}</b> de {{artist}}, ganadora del concurso "Canción del Buen Amor 2026".',
    'music.spotify': 'O ir a Spotify',
    'music.pause': 'Pausar',
    'music.play': 'Play BGM',
    'music.spotify.title': 'Abrir en Spotify',

    // Hero Extra
    'hero.est': 'Est. 1994 // Puebla, MX',

    // Footer
    'footer.title.main': '¿Hablamos de negocios,',
    'footer.title.sub': 'o de la {{highlight}} del mundo?',
    'footer.title.highlight': 'ruina',
    'footer.direct': 'Formulario Directo',
    'footer.online': '[ En línea ]',
    'footer.send': 'Enviar Transmisión',
    'footer.rights': 'Todos los derechos reservados.',
    'footer.made': 'Hecho con frustración al capitalismo, y código.',
    'footer.comms': 'Comms_',
    'footer.base': 'Base_',
    'footer.net': 'Red_',
    'footer.subtitle': 'Para contrataciones de servicios web, conferencias, colaboraciones musicales o debates filosóficos a las 3 AM.',
    'footer.links.comms': 'Transmisión & Base',
    'footer.links.net': 'Redes & Ecosistema',
    'footer.form.name.label': 'Nombre / Entidad',
    'footer.form.name.ph': 'Escribe tu identidad...',
    'footer.form.email.label': 'Correo Electrónico',
    'footer.form.email.ph': 'correo@ejemplo.com',
    'footer.form.subject': 'Contacto desde Catálogo Humano',
    'footer.form.topic.label': 'Motivo del Encuentro',
    'footer.form.topic.opt1': 'Selecciona un motivo...',
    'footer.form.topic.opt2': 'Servicios Web',
    'footer.form.topic.opt3': 'Juegos Web',
    'footer.form.topic.opt4': 'Gestión Cultural & Conferencias',
    'footer.form.topic.opt5': 'Colaboración Musical',
    'footer.form.topic.opt6': 'Otros asuntos (quejas existenciales)',
    'footer.form.msg.label': 'Mensaje',
    'footer.form.msg.ph': 'Detalla tu idea o crisis...',

    // Oracle Page
    'orc.back': '[ Base Central ]',
    'orc.badge': 'Oráculo de Producción',
    'orc.title1': 'Dime qué quieres',
    'orc.title2': 'y te diré la verdad.',
    'orc.desc': '¿Tienes un evento en mente? El algoritmo evalúa su viabilidad (con una dosis severa de escepticismo). Ponle nombre, tira los dados y veamos a qué nos enfrentamos.',
    'orc.input.label': 'Inyecta el nombre del proyecto:',
    'orc.input.placeholder': 'Ej. Cyberpunk Fest...',
    'orc.btn.spin': 'Tirar los dados del destino',
    'orc.diag': 'Diagnóstico de Realidad Generado',
    'orc.lbl1': 'Formato Cortocircuito',
    'orc.lbl2': 'Sede Temeraria',
    'orc.lbl3': 'Público Involuntario',
    'orc.lbl4': 'Capital Disponible',
    'orc.btn.action': 'Sacar del Pizarrón',
    'orc.btn.reset': '[ Re-calcular ]',

    // Arcade
    'arc.back': '[ Base Central ]',
    'arc.restricted': 'ARCHIVOS RESTRINGIDOS',
    'arc.sisyphus': '—Sísifo',
    'arc.desc': 'Porque la vida es un RPG roto sin manual. Desconecta de la hiperproductividad y ríete del algoritmo.',
    'arc.game1': 'Pong de Debate',
    'arc.game2': 'Cartas Políticas',
    'arc.game3': 'Gato de Ideas',
    'arc.game4': 'Simulador de Curador',

    // Game: ArtRPG
    'game.rpg.title': 'SIMULADOR DE INAUGURACIÓN',
    'game.rpg.goal': 'Sobrevive al evento de arte',
    'game.rpg.start': 'INICIAR CRISIS',
    'game.rpg.restart': 'VOLVER AL FRACASO',
    'game.rpg.q1': 'El catering no ha llegado y la inauguración empieza en 1 hora. La gente está haciendo fila.',
    'game.rpg.q1.a': 'Servir vino barato en vasos de plástico tapando la marca.',
    'game.rpg.q1.b': 'Declarar que el vacío estomacal es el concepto central de la obra.',
    'game.rpg.q2a': 'Serviste vino barato. Los críticos se emborracharon rápido y están gritando.',
    'game.rpg.q2a.a': 'Dar un discurso incomprensible con citas de Foucault.',
    'game.rpg.q2a.b': 'Ignorarlos y adular a los inversionistas de traje.',
    'game.rpg.q2b': 'El público cree que el hambre es performance. Están confundidos y levemente molestos.',
    'game.rpg.q2b.a': 'Empezar a gritar en alemán para intimidarlos y parecer intelectual.',
    'game.rpg.q2b.b': 'Huir sutilmente por la puerta de carga trasera.',
    'game.rpg.q3a': 'Tras tu discurso, un millonario excéntrico cree que eres la reencarnación de Duchamp.',
    'game.rpg.q3a.a': 'Venderle un extintor del museo por 500,000 USD.',
    'game.rpg.q3a.b': 'Insultar su linaje por no entender el meta-mensaje.',
    'game.rpg.q3b': 'Los inversionistas aceptan tu adulación, pero exigen censurar una obra política.',
    'game.rpg.q3b.a': 'Censurar la obra por el bien del capital.',
    'game.rpg.q3b.b': 'Lanzarles el resto del vino barato en protesta.',
    'game.rpg.q3c': 'El público guarda un silencio sepulcral. Creen que tu dialecto es una denuncia al sistema.',
    'game.rpg.q3c.a': 'Llevarlo al límite y prenderle fuego a la obra principal.',
    'game.rpg.q3c.b': 'Quedarte en silencio absoluto mirando el techo.',
    'game.rpg.q3d': 'Escapas al callejón. Te encuentras al DJ y al proveedor del catering fumando.',
    'game.rpg.q3d.a': 'Robar los canapés, esconderte y comer llorando.',
    'game.rpg.q3d.b': 'Convencerlos de montar la expo clandestina ahí mismo.',
    // Endings
    'game.rpg.e1': 'FINAL 1: VENDIDO\nEres rico. El gremio te odia. Vives en Mónaco cuestionando tu integridad mientras bebes champaña real. Has triunfado (económicamente).',
    'game.rpg.e2': 'FINAL 2: MÁRTIR DEL UNDERGROUND\nEl millonario te demanda. Eres pobre, pero la crítica te adora. Te vuelves una leyenda indomable en los bares lúgubres de la ciudad.',
    'game.rpg.e3': 'FINAL 3: BURÓCRATA CULTURAL\nTe cancelan masivamente en Twitter. A cambio, el gobierno te patrocina galerías vitalicias. Has matado tu alma, pero pagas la renta a tiempo.',
    'game.rpg.e4': 'FINAL 4: PERFORMANCE CARCELARIO\nPasas la noche en los separos. Sorprendentemente, al día siguiente las revistas declaran que fue una "intervención disruptiva". Eres un genio intocable.',
    'game.rpg.e5': 'FINAL 5: ARTE EFÍMERO TOTAL\nEl museo se reduce a cenizas. El seguro no cubre el "performance". Terminas con deudas de por vida pero con la anécdota más increíble del siglo.',
    'game.rpg.e6': 'FINAL 6: MEME HUMANO\nTe graban en TikTok mirando el techo. Te vuelves el meme del mes. Las marcas te buscan para anuncios de bancos. Pierdes tu prestigio pero ganas likes canjeables por ansiedad.',
    'game.rpg.e7': 'FINAL 7: GLUTEN FREE\nLa expo fracasa sin ti. El galerista te despide. Pero descubriste que los canapés de salmón estaban deliciosos. Triunfo personal.',
    'game.rpg.e8': 'FINAL 8: CONTRACULTURA ALLEY\nEl callejón se vuelve el nuevo happening histórico. Destruyes el elitismo del cubo blanco. Comienzas un movimiento que se estudiará en los libros.',

    // Games - General
    'game.objective': 'Objetivo: ',
    'game.retry': 'REINTENTAR',
    'game.insert': 'INSERT COIN',

    // Game: Pong
    'game.pong.thesis': 'Tesis (Tú)',
    'game.pong.antithesis': 'Antítesis (Algoritmo)',
    'game.pong.win': '¡GANASTE EL DEBATE!',
    'game.pong.lose': 'LA MÁQUINA TE REFUTÓ',
    'game.pong.title': 'PONG DE DEBATE',
    'game.pong.goal': 'Llega a 5 puntos',
    'game.pong.controls': 'Usa el ratón o dedo para mover tu argumento',

    // Game: TicTacToe
    'game.ttt.goal': '3 ideas alineadas',
    'game.ttt.win': '¡Hegemonía de la {{winner}}!',
    'game.ttt.reason': 'Razón (X)',
    'game.ttt.tradition': 'Tradición (O)',
    'game.ttt.draw': 'Aporía: Empate irresoluble.',
    'game.ttt.turn': 'Turno: ',
    'game.ttt.you': 'Tú (X)',
    'game.ttt.bot': 'Máquina Dogmática (O)',
    'game.ttt.reset': 'DECONSTRUIR SISTEMA',
    'game.ttt.log.start': 'El debate comienza. Elige una premisa.',
    'game.ttt.log.reset': 'Nueva tabula rasa. Comienza el debate.',

    // Game: Political Uno
    'game.uno.goal': 'Quédate sin cartas para ganar la elección',
    'game.uno.msg.start': 'La cámara está en sesión.',
    'game.uno.msg.turn': 'Legislador, es tu turno. Juega por color o ideología.',
    'game.uno.msg.moche.win': 'Aplicaste un Moche. ¡Multa de 2 cartas!',
    'game.uno.msg.moche.lose': 'Te aplicaron un Moche. ¡Multa de 2 cartas!',
    'game.uno.msg.fuero.win': 'Activaste Fuero. Se salta un turno.',
    'game.uno.msg.fuero.lose': 'El rival tiene Fuero. Se salta un turno.',
    'game.uno.msg.alliance': '¡Alianza partidista! Cambia el flujo político.',
    'game.uno.msg.win': '¡Ganaste las elecciones y tienes mayoría absoluta!',
    'game.uno.msg.lose': 'El sistema te ha vencido. Eres oposición plurinominal.',
    'game.uno.msg.error': 'Objeción: Conflicto de interés. Juega otro color/símbolo.',
    'game.uno.msg.draw': 'Robaste presupuesto. Intervención de la oposición...',
    'game.uno.msg.opposition': 'El bloque opositor está maquinando su voto...',
    'game.uno.msg.cpu_play': 'La oposición ha votado. Tu turno.',
    'game.uno.msg.cpu_draw': 'La oposición desvió recursos (robó carta). Tu turno.',
    'game.uno.label.draw': 'ROBAR',
    'game.uno.label.deck': 'Erario',
    'game.uno.label.pile': 'Curul',
    'game.uno.label.hand': 'Tus Iniciativas',
    'game.uno.label.reset': 'NUEVA LEGISLATURA',
    'game.uno.action.moche': 'Moche',
    'game.uno.action.fuero': 'Fuero',
    'game.uno.action.alliance': 'Reversa',

    // Game: FestJump
    'game.fest.back': 'Volver al Inicio',
    'game.fest.desc': 'Prototipo jugable de gamificación para festivales. Retiene atención de usuarios, entrega códigos promocionales por hitos de distancia, y convierte el engagement en compras (tickets o merch).',
    'game.fest.title': 'Altitud',
    'game.fest.codes': 'Códigos',
    'game.fest.hint': 'Sube 500m+',
    'game.fest.objective': 'Mueve el ratón o el dedo. Sube para desbloquear descuentos para el festival 2026.',
    'game.fest.over': 'Game Over. Altura: {{score}}m',
    'game.fest.discount5': 'FEST2026 (5% Descuento)',
    'game.fest.discount10': 'BEATS26 (10% Descuento)',
    'game.fest.discountVIP': 'VIPFEST (Acces/Bebida)'
  },
  en: {
    'nav.home': 'Home',
    'nav.back_to_home': 'Back to Home',
    // Hero
    'hero.title1': 'Human',
    'hero.title2': 'Catalog',
    'hero.job': 'Strategist, cultural manager and experience architect.',
    'hero.desc': 'Welcome to my neural network: an interactive space where music, code, and critical thinking collide to hack the monotony of reality.',
    'hero.inventory': 'Inventory',
    'hero.services': 'Services (Stats)',
    'hero.years': 'Years',

    'home.testerTitle': 'Interactive Beta Tester',
    'home.oracleTitle1': 'Production ',
    'home.oracleTitle2': 'Oracle',
    'home.oracleDesc': 'Test the viability of your idea (and my patience) with this ironic project generator.',
    'home.rollDice': 'Roll the Dice',

    'eco.label': '01 // Ecosystem',
    'eco.title': '01 // Ecosystem',
    'eco.multiverse': 'Creative',
    'eco.creative': '—Multiverse',
    'eco.desc': 'Every project is a synapse. An open file where I cross disciplines to generate short circuits in linear thinking and dodge the algorithm.',
    'eco.cat1': 'Content',
    'eco.proj1.desc': 'Space dedicated to the daily creation of cultural and philosophical content. Reflections on life that do not ask for permission.',
    'eco.proj1.link': 'Explore Content',
    'eco.cat2': 'Blog & Thought',
    'eco.proj2.desc': 'My personal blog. Extended thoughts, life as an RPG, the soul as a flow and miscellaneous essays on exhaustion and art.',
    'eco.proj2.link': 'Read Blog',
    'eco.cat3': 'Music',
    'eco.proj3.desc': 'Experiential sonic integration. Compositions that explore bonds, loneliness and life in a disposable era.',
    'eco.proj3.link': 'Listen on Spotify',
    'eco.cat4': 'Arcade & Game Design',
    'eco.proj4.desc': 'Game design and mechanics focused on rethinking the algorithmic and political \'Dungeon Master\'. Debate Pong and more.',
    'eco.proj4.link': 'Insert Coin',
    'eco.cat5': 'Interactive Mockup',
    'eco.proj5.title': 'An idea for your event',
    'eco.proj5.desc': 'Gamification retains attention where traditional marketing fails. Asynchronous hyper-casual prototype for massive festivals.',
    'eco.proj5.link': 'Play the Mockup',

    'serv.title': '02 // Skill Inventory',
    'serv.tree': 'Skill ',
    'serv.skills': 'Tree',
    'serv.desc': 'The backend of my ecosystem. Tactical deployment tools where I transfer abstract theory into operational and tangible results.',
    'serv.s1.title': 'Strategy & Mega-Production',
    'serv.s1.desc': 'Translating vision into flawless logistics. From hosting international exhibitions for local governments and IP, to raising entire festivals.',
    'serv.s2.title': 'Cultural Policy & Social Impact',
    'serv.s2.desc': 'Specialist in community reactivation. I have designed sociocultural programs (STEAM) weaving global and local alliances.',
    'serv.s3.title': 'Thought, Narrative & Public Speaking',
    'serv.s3.desc': 'Discourse design, scripts, and texts that capture attention while respecting the reader\'s intelligence.',
    'serv.s4.title': 'Code, Interface & Web Subversion',
    'serv.s4.desc': 'Software is the infrastructure of the present. I build tailor-made web ecosystems and gamified mechanics for creators.',

    'mani.title': '03 // Manifesto',
    'mani.h3': 'Sisyphus,',
    'mani.h3.sub': 'but with a customized HUD.',
    'mani.quote': '"I am a philosopher who learned to balance budgets in Excel, or a producer infiltrating academia."',
    'mani.p1': 'My logbook is not a straight line, it is a map of collisions. I studied Philosophy at BUAP, Aesthetic Avant-gardes at the University of Salamanca and finished with a Master\'s in Cultural Management. I operate from MX not just to observe, but to detonate intellect and creative energy on a massive scale.',
    'mani.p2_1': 'In my network, inter-institutional agendas converge with dozens of embassies, social impact auctions, and private investment strategies. I have taken these visions from paper to operational muscle: coordinating ',
    'mani.p2_2': 'more than 600 events',
    'mani.p2_3': ', achieving ',
    'mani.p2_4': '+500,000 direct impacts',
    'mani.p2_5': ' and extending these ecosystems to ',
    'mani.p2_6': '10 countries',
    'mani.p2_7': '.',
    'mani.p3': 'I know contemporary overstimulation firsthand; that\'s why I create my own emergency exits. Programming an interactive platform or designing a macro-festival requires the same technical precision: ordering chaos and injecting human meaning right where the algorithm demands noise.',
    'mani.box1.title': 'Neural Input',
    'mani.box1.desc': 'Philosophy / Avant-gardes / Design',
    'mani.box2.title': 'Processing',
    'mani.box2.desc': '+600 Events / Dynamic Management',
    'mani.box3.title': 'Deployed Output',
    'mani.box3.desc': '+500k Impacts in 10 Countries',

    // Footer Extra
    'footer.location': 'Puebla, Mexico',
    'footer.form.body.name': 'Name',
    'footer.form.body.email': 'Email',
    'footer.form.body.topic': 'Reason',
    'footer.form.body.msg': 'Message',

    // Ecosystem Extra
    'eco.proj4.title': 'Arcade: 8-bit Parodies',

    // Generator Extra
    'orc.default_name': 'Big Project',

    // Music Player
    'music.label': 'Site Music',
    'music.desc': 'Listen to <b>{{title}}</b> by {{artist}}, winner of the "Song of Good Love 2026" contest.',
    'music.spotify': 'Or go to Spotify',
    'music.pause': 'Pause',
    'music.play': 'Play BGM',
    'music.spotify.title': 'Open on Spotify',

    // Hero Extra
    'hero.est': 'Est. 1994 // Puebla, MX',

    'footer.title.main': 'Shall we talk business,',
    'footer.title.sub': 'or the {{highlight}} of the world?',
    'footer.title.highlight': 'ruin',
    'footer.direct': 'Direct Form',
    'footer.online': '[ Online ]',
    'footer.send': 'Send Transmission',
    'footer.rights': 'All rights reserved.',
    'footer.made': 'Made with frustration towards capitalism, and code.',
    'footer.comms': 'Comms_',
    'footer.base': 'Base_',
    'footer.net': 'Net_',
    'footer.subtitle': 'For web services, public speaking, musical collaborations, or philosophical debates at 3 AM.',
    'footer.links.comms': 'Transmission & Base',
    'footer.links.net': 'Network & Ecosystem',
    'footer.form.name.label': 'Name / Entity',
    'footer.form.name.ph': 'Write your identity...',
    'footer.form.email.label': 'Email Address',
    'footer.form.email.ph': 'email@example.com',
    'footer.form.subject': 'Contact from Human Catalog',
    'footer.form.topic.label': 'Reason for Encounter',
    'footer.form.topic.opt1': 'Select a reason...',
    'footer.form.topic.opt2': 'Web Services',
    'footer.form.topic.opt3': 'Web Games',
    'footer.form.topic.opt4': 'Cultural Management & Conferences',
    'footer.form.topic.opt5': 'Musical Collaboration',
    'footer.form.topic.opt6': 'Other matters (existential complaints)',
    'footer.form.msg.label': 'Message',
    'footer.form.msg.ph': 'Detail your idea or crisis...',

    'orc.back': '[ Central Base ]',
    'orc.badge': 'Production Oracle',
    'orc.title1': 'Tell me what you want',
    'orc.title2': 'and I will tell you the truth.',
    'orc.desc': 'Have an event in mind? The algorithm evaluates its viability (with a severe dose of skepticism). Name it, roll the dice, and let\'s see.',
    'orc.input.label': 'Inject project name:',
    'orc.input.placeholder': 'E.g. Cyberpunk Fest...',
    'orc.btn.spin': 'Roll the Dice of Destiny',
    'orc.diag': 'Generated Reality Diagnosis',
    'orc.lbl1': 'Short Circuit Format',
    'orc.lbl2': 'Reckless Venue',
    'orc.lbl3': 'Involuntary Audience',
    'orc.lbl4': 'Available Capital',
    'orc.btn.action': 'Take it off the Board',
    'orc.btn.reset': '[ Re-calculate ]',

    // Arcade
    'arc.back': '[ Central Base ]',
    'arc.restricted': 'RESTRICTED ARCHIVES',
    'arc.sisyphus': '—Sisyphus',
    'arc.desc': 'Because life is a broken RPG with no manual. Disconnect from hyper-productivity and laugh at the algorithm.',
    'arc.game1': 'Debate Pong',
    'arc.game2': 'Political Cards',
    'arc.game3': 'Ideas Tic-Tac-Toe',
    'arc.game4': 'Curator Simulator',

    // Game: ArtRPG
    'game.rpg.title': 'INAUGURATION SIMULATOR',
    'game.rpg.goal': 'Survive the art event',
    'game.rpg.start': 'START CRISIS',
    'game.rpg.restart': 'RETURN TO FAILURE',
    'game.rpg.q1': 'The catering hasn\'t arrived and the opening starts in 1 hour. People are lining up.',
    'game.rpg.q1.a': 'Serve cheap wine in plastic cups, hiding the brand.',
    'game.rpg.q1.b': 'Declare that starvation is the central concept of the exhibition.',
    'game.rpg.q2a': 'You served cheap wine. The critics got drunk quickly and are shouting.',
    'game.rpg.q2a.a': 'Give an incomprehensible speech quoting Foucault.',
    'game.rpg.q2a.b': 'Ignore them and flatter the investors in suits.',
    'game.rpg.q2b': 'The audience thinks starvation is a performance. They are confused and slightly annoyed.',
    'game.rpg.q2b.a': 'Start shouting in German to intimidate them and look intellectual.',
    'game.rpg.q2b.b': 'Subtly flee through the back loading door.',
    'game.rpg.q3a': 'After your speech, an eccentric millionaire thinks you are the reincarnation of Duchamp.',
    'game.rpg.q3a.a': 'Sell him a museum fire extinguisher for 500,000 USD.',
    'game.rpg.q3a.b': 'Insult his lineage for not understanding the meta-message.',
    'game.rpg.q3b': 'The investors accept your flattery, but demand censoring a political artwork.',
    'game.rpg.q3b.a': 'Censor the artwork for the sake of capital.',
    'game.rpg.q3b.b': 'Throw the rest of the cheap wine in their faces in protest.',
    'game.rpg.q3c': 'The audience is dead silent. They think your dialect is a denunciation of the system.',
    'game.rpg.q3c.a': 'Take it to the limit and set fire to the main artwork.',
    'game.rpg.q3c.b': 'Stay in absolute silence staring at the ceiling.',
    'game.rpg.q3d': 'You escape to the alley. You find the DJ and the caterer smoking.',
    'game.rpg.q3d.a': 'Steal the canapés, hide, and eat while crying.',
    'game.rpg.q3d.b': 'Convince them to set up a clandestine expo right there.',
    // Endings
    'game.rpg.e1': 'ENDING 1: SELLOUT\nYou are rich. The guild hates you. You live in Monaco questioning your integrity while drinking real champagne. You have succeeded (economically).',
    'game.rpg.e2': 'ENDING 2: UNDERGROUND MARTYR\nThe millionaire sues you. You are poor, but the critics adore you. You become an indomitable legend in the city\'s gloomy bars.',
    'game.rpg.e3': 'ENDING 3: CULTURAL BUREAUCRAT\nYou are massively canceled on Twitter. In return, the government sponsors your galleries for life. You killed your soul, but pay rent on time.',
    'game.rpg.e4': 'ENDING 4: PRISON PERFORMANCE\nYou spend the night in jail. Surprisingly, the next day magazines declare it a "disruptive intervention". You are an untouchable genius.',
    'game.rpg.e5': 'ENDING 5: TOTAL EPHEMERAL ART\nThe museum is reduced to ashes. Insurance doesn\'t cover "performances". You end up with lifelong debt but the most incredible anecdote of the century.',
    'game.rpg.e6': 'ENDING 6: HUMAN MEME\nYou are recorded on TikTok staring at the ceiling. You become the meme of the month. Brands seek you for bank ads. You lose your prestige but gain likes exchangeable for anxiety.',
    'game.rpg.e7': 'ENDING 7: GLUTEN FREE\nThe expo fails without you. The gallery owner fires you. But you discovered the salmon canapés were delicious. Personal triumph.',
    'game.rpg.e8': 'ENDING 8: ALLEY COUNTERCULTURE\nThe alley becomes the new historical happening. You destroy the elitism of the white cube. You start a movement that will be studied in books.',

    // Games - General
    'game.objective': 'Objective: ',
    'game.retry': 'RETRY',
    'game.insert': 'INSERT COIN',

    // Game: Pong
    'game.pong.thesis': 'Thesis (You)',
    'game.pong.antithesis': 'Antithesis (Algorithm)',
    'game.pong.win': 'YOU WON THE DEBATE!',
    'game.pong.lose': 'THE MACHINE REFUTED YOU',
    'game.pong.title': 'DEBATE PONG',
    'game.pong.goal': 'Reach 5 points',
    'game.pong.controls': 'Use mouse or finger to move your argument',

    // Game: TicTacToe
    'game.ttt.goal': '3 aligned ideas',
    'game.ttt.win': '{{winner}} Hegemony!',
    'game.ttt.reason': 'Reason (X)',
    'game.ttt.tradition': 'Tradition (O)',
    'game.ttt.draw': 'Aporia: Irresolvable draw.',
    'game.ttt.turn': 'Turn: ',
    'game.ttt.you': 'You (X)',
    'game.ttt.bot': 'Dogmatic Machine (O)',
    'game.ttt.reset': 'DECONSTRUCT SYSTEM',
    'game.ttt.log.start': 'The debate begins. Choose a premise.',
    'game.ttt.log.reset': 'New tabula rasa. The debate begins.',

    // Game: Political Uno
    'game.uno.goal': 'Run out of cards to win the election',
    'game.uno.msg.start': 'The chamber is in session.',
    'game.uno.msg.turn': 'Legislator, it is your turn. Play by color or ideology.',
    'game.uno.msg.moche.win': 'You applied a Moche (bribe). 2-card fine!',
    'game.uno.msg.moche.lose': 'They applied a Moche to you. 2-card fine!',
    'game.uno.msg.fuero.win': 'You activated Fuero (immunity). Skip a turn.',
    'game.uno.msg.fuero.lose': 'The rival has Fuero. Skip a turn.',
    'game.uno.msg.alliance': 'Partisan alliance! Changes the political flow.',
    'game.uno.msg.win': 'You won the elections and have an absolute majority!',
    'game.uno.msg.lose': 'The system has defeated you. You are in the proportional opposition.',
    'game.uno.msg.error': 'Objection: Conflict of interest. Play another color/symbol.',
    'game.uno.msg.draw': 'You stole from the budget. Opposition intervention...',
    'game.uno.msg.opposition': 'The opposition block is plotting their vote...',
    'game.uno.msg.cpu_play': 'The opposition has voted. Your turn.',
    'game.uno.msg.cpu_draw': 'The opposition diverted resources (drew a card). Your turn.',
    'game.uno.label.draw': 'DRAW',
    'game.uno.label.deck': 'Treasury',
    'game.uno.label.pile': 'Seat',
    'game.uno.label.hand': 'Your Initiatives',
    'game.uno.label.reset': 'NEW LEGISLATURE',
    'game.uno.action.moche': 'Bribe',
    'game.uno.action.fuero': 'Immunity',
    'game.uno.action.alliance': 'Reverse',

    // Game: FestJump
    'game.fest.back': 'Back to Home',
    'game.fest.desc': 'Playable gamification prototype for festivals. Retains user attention, delivers promo codes for distance milestones, and converts engagement into purchases (tickets or merch).',
    'game.fest.title': 'Altitude',
    'game.fest.codes': 'Codes',
    'game.fest.hint': 'Climb 500m+',
    'game.fest.objective': 'Move the mouse or finger. Climb to unlock discounts for the 2026 festival.',
    'game.fest.over': 'Game Over. Altitude: {{score}}m',
    'game.fest.discount5': 'FEST2026 (5% Discount)',
    'game.fest.discount10': 'BEATS26 (10% Discount)',
    'game.fest.discountVIP': 'VIPFEST (Access/Drink)'
  },
  fr: {
    'nav.home': 'Accueil',
    'nav.back_to_home': 'Retour à l\'accueil',
    // Hero
    'hero.title1': 'Catalogue',
    'hero.title2': 'Humain',
    'hero.job': 'Stratège, gestionnaire culturel et architecte d\'expériences.',
    'hero.desc': 'Bienvenue dans mon réseau de neurones : un espace interactif où la musique, le code et la pensée critique s\'entrechoquent pour pirater la monotonie de la réalité.',
    'hero.inventory': 'Inventaire',
    'hero.services': 'Services (Stats)',
    'hero.years': 'Ans',

    'home.testerTitle': 'Bêta Testeur Interactif',
    'home.oracleTitle1': 'Oracle de ',
    'home.oracleTitle2': 'Production',
    'home.oracleDesc': 'Testez la viabilité de votre idée (et ma patience) avec ce générateur de projet ironique.',
    'home.rollDice': 'Lancer les dés',

    'eco.label': '01 // Écosystème',
    'eco.title': '01 // Écosystème',
    'eco.multiverse': 'Créatif',
    'eco.creative': '—Multivers',
    'eco.desc': 'Chaque projet est une synapse. Un dossier ouvert où je croise les disciplines pour générer des courts-circuits dans la pensée linéaire et esquiver l\'algorithme.',
    'eco.cat1': 'Contenu',
    'eco.proj1.desc': 'Espace dédié à la création quotidienne de contenu culturel et philosophique. Des réflexions sur la vie.',
    'eco.proj1.link': 'Explorer le contenu',
    'eco.cat2': 'Blog & Pensée',
    'eco.proj2.desc': 'Mon blog personnel. Pensées étendues, la vie comme un RPG, des essais divers sur l\'épuisement et l\'art.',
    'eco.proj2.link': 'Lire le blog',
    'eco.cat3': 'Musique',
    'eco.proj3.desc': 'Intégration sonore expérientielle. Compositions qui explorent les liens, la solitude et la vie à une époque jetable.',
    'eco.proj3.link': 'Écouter sur Spotify',
    'eco.cat4': 'Arcade & Game Design',
    'eco.proj4.desc': 'Conception et mécanique de jeu axées sur la refonte du \'Dungeon Master\' algorithmique et politique. Debate Pong et plus.',
    'eco.proj4.link': 'Insérer une pièce',
    'eco.cat5': 'Maquette Interactive',
    'eco.proj5.title': 'Une idée pour votre événement',
    'eco.proj5.desc': 'La gamification retient l\'attention là où le marketing traditionnel échoue. Prototype hyper-casual asynchrone pour les grands festivals.',
    'eco.proj5.link': 'Jouer la maquette',

    'serv.title': '02 // Inventaire des Compétences',
    'serv.tree': 'Arbre de ',
    'serv.skills': 'Compétences',
    'serv.desc': 'Le backend de mon écosystème. Outils de déploiement tactique où je transfère la théorie abstraite en résultats opérationnels.',
    'serv.s1.title': 'Stratégie et Mégaproduction',
    'serv.s1.desc': 'Traduire la vision en logistique impeccable. De l\'hébergement d\'expositions internationales à la création de festivals massifs.',
    'serv.s2.title': 'Politique Culturelle & Impact Social',
    'serv.s2.desc': 'Spécialiste en réactivation communautaire. J\'ai conçu des programmes socioculturels (STEAM) tissant des alliances globales et locales.',
    'serv.s3.title': 'Pensée, Récit & Art Oratoire',
    'serv.s3.desc': 'Conception de discours, scénarios et textes qui captent l\'attention tout en respectant l\'intelligence du lecteur.',
    'serv.s4.title': 'Code, Interface et Subversion Web',
    'serv.s4.desc': 'Je construis des écosystèmes web sur mesure et des mécaniques gamifiées pour les créateurs qui recherchent des formats uniques.',

    'mani.title': '03 // Manifeste',
    'mani.h3': 'Sisyphe,',
    'mani.h3.sub': 'mais avec un HUD personnalisé.',
    'mani.quote': '"Je suis un philosophe qui a appris à équilibrer des budgets sur Excel, ou un producteur infiltré dans le milieu universitaire."',
    'mani.p1': 'Mon journal de bord n\'est pas une ligne droite, c\'est une carte de collisions. J\'ai étudié la philosophie à la BUAP, les avant-gardes esthétiques à l\'Université de Salamanque et j\'ai terminé par une maîtrise en gestion culturelle. J\'opère depuis MX non seulement pour observer, mais pour faire exploser l\'intellect et l\'énergie créative à grande échelle.',
    'mani.p2_1': 'Dans mon réseau convergent des agendas interinstitutionnels avec des dizaines d\'ambassades, des ventes aux enchères à impact social et des stratégies d\'investissement privé. J\'ai fait passer ces visions du papier au muscle opérationnel : en coordonnant ',
    'mani.p2_2': 'plus de 600 événements',
    'mani.p2_3': ', en obtenant ',
    'mani.p2_4': '+500 000 impacts directs',
    'mani.p2_5': ' et en étendant ces écosystèmes à ',
    'mani.p2_6': '10 pays',
    'mani.p2_7': '.',
    'mani.p3': 'Je connais la surstimulation contemporaine de première main ; c\'est pourquoi je crée mes propres sorties de secours. Programmer une plateforme interactive ou concevoir un macro-festival exige la même précision technique : ordonner le chaos et injecter du sens humain là où l\'algorithme exige du bruit.',
    'mani.box1.title': 'Entrée Neurale',
    'mani.box1.desc': 'Philosophie / Avant-gardes / Design',
    'mani.box2.title': 'Traitement',
    'mani.box2.desc': '+600 Événements / Gestion Dynamique',
    'mani.box3.title': 'Sortie Déployée',
    'mani.box3.desc': '+500k Impacts dans 10 Pays',

    // Footer Extra
    'footer.location': 'Puebla, Mexique',
    'footer.form.body.name': 'Nom',
    'footer.form.body.email': 'Email',
    'footer.form.body.topic': 'Motif',
    'footer.form.body.msg': 'Message',

    // Ecosystem Extra
    'eco.proj4.title': 'Arcade : Parodies 8 bits',

    // Generator Extra
    'orc.default_name': 'Grand Projet',

    // Music Player
    'music.label': 'Musique du site',
    'music.desc': 'Écoutez <b>{{title}}</b> de {{artist}}, gagnant du concours "Chanson du Bon Amour 2026".',
    'music.spotify': 'Ou aller sur Spotify',
    'music.pause': 'Pause',
    'music.play': 'Play BGM',
    'music.spotify.title': 'Ouvrir sur Spotify',

    // Hero Extra
    'hero.est': 'Basé à Puebla, MX // 1994',

    'footer.title.main': 'Parlons-nous affaires,',
    'footer.title.sub': 'ou de la {{highlight}} du monde ?',
    'footer.title.highlight': 'ruine',
    'footer.direct': 'Formulaire Direct',
    'footer.online': '[ En ligne ]',
    'footer.send': 'Envoyer la Transmission',
    'footer.rights': 'Tous droits réservés.',
    'footer.made': 'Fait avec frustration envers le capitalisme, et du code.',
    'footer.comms': 'Comms_',
    'footer.base': 'Base_',
    'footer.net': 'Net_',
    'footer.subtitle': 'Pour des services web, des conférences, des collaborations musicales ou des débats philosophiques à 3h du matin.',
    'footer.links.comms': 'Transmission & Base',
    'footer.links.net': 'Réseaux & Écosystème',
    'footer.form.name.label': 'Nom / Entité',
    'footer.form.name.ph': 'Écrivez votre identité...',
    'footer.form.email.label': 'Adresse E-mail',
    'footer.form.email.ph': 'email@exemple.com',
    'footer.form.subject': 'Contact depuis le Catalogue Humain',
    'footer.form.topic.label': 'Motif de la Rencontre',
    'footer.form.topic.opt1': 'Sélectionnez un motif...',
    'footer.form.topic.opt2': 'Services Web',
    'footer.form.topic.opt3': 'Jeux Web',
    'footer.form.topic.opt4': 'Gestion Culturelle & Conférences',
    'footer.form.topic.opt5': 'Collaboration Musicale',
    'footer.form.topic.opt6': 'Autres affaires (plaintes existentielles)',
    'footer.form.msg.label': 'Message',
    'footer.form.msg.ph': 'Détaillez votre idée ou crise...',

    'orc.back': '[ Base Centrale ]',
    'orc.badge': 'Oracle de Production',
    'orc.title1': 'Dis-moi ce que tu veux',
    'orc.title2': 'et je te dirai la vérité.',
    'orc.desc': 'Vous avez un événement en tête? L\'algorithme évalue sa viabilité. Nommez-le, lancez les dés, et voyons.',
    'orc.input.label': 'Injecter le nom du projet:',
    'orc.input.placeholder': 'Ex. Cyberpunk Fest...',
    'orc.btn.spin': 'Lancer les dés du destin',
    'orc.diag': 'Diagnostic de Réalité Généré',
    'orc.lbl1': 'Format Court-circuit',
    'orc.lbl2': 'Lieu Imprudent',
    'orc.lbl3': 'Public Involontaire',
    'orc.lbl4': 'Capital Disponible',
    'orc.btn.action': 'Prenez-le du tableau',
    'orc.btn.reset': '[ Re-calculer ]',

    // Arcade
    'arc.back': '[ Base Centrale ]',
    'arc.restricted': 'ARCHIVES RESTREINTES',
    'arc.sisyphus': '—Sisyphe',
    'arc.desc': 'Parce que la vie est un RPG cassé sans manuel. Déconnectez-vous de l\'hyperproductivité et riez de l\'algorithme.',
    'arc.game1': 'Pong de Débat',
    'arc.game2': 'Cartes Politiques',
    'arc.game3': 'Morpion d\'Idées',
    'arc.game4': 'Simulateur de Curateur',

    // Game: ArtRPG
    'game.rpg.title': 'SIMULATEUR D\'INAUGURATION',
    'game.rpg.goal': 'Survis à l\'événement...',
    'game.rpg.start': 'LANCER LA CRISE',
    'game.rpg.restart': 'RETOURNER À L\'ÉCHEC',
    'game.rpg.q1': 'Le traiteur n\'est pas arrivé et le vernissage commence dans 1 heure. Les gens font la queue.',
    'game.rpg.q1.a': 'Servir du vin bon marché dans des gobelets en plastique en cachant la marque.',
    'game.rpg.q1.b': 'Déclarer que le ventre vide est le concept central de l\'exposition.',
    'game.rpg.q2a': 'Vous avez servi du vin bon marché. Les critiques se sont enivrés rapidement et crient.',
    'game.rpg.q2a.a': 'Faire un discours incompréhensible en citant Foucault.',
    'game.rpg.q2a.b': 'Les ignorer et flatter les investisseurs en costume.',
    'game.rpg.q2b': 'Le public pense que la faim est une performance. Ils sont confus et agacés.',
    'game.rpg.q2b.a': 'Commencer à crier en allemand pour les intimider et paraître intellectuel.',
    'game.rpg.q2b.b': 'Fuir subtilement par la porte de chargement arrière.',
    'game.rpg.q3a': 'Après votre discours, un millionnaire excentrique pense que vous êtes la réincarnation de Duchamp.',
    'game.rpg.q3a.a': 'Lui vendre un extincteur de musée pour 500 000 USD.',
    'game.rpg.q3a.b': 'Insulter sa lignée pour ne pas avoir compris le méta-message.',
    'game.rpg.q3b': 'Les investisseurs acceptent votre flatterie, mais exigent de censurer une œuvre politique.',
    'game.rpg.q3b.a': 'Censurer l\'œuvre pour le bien du capital.',
    'game.rpg.q3b.b': 'Leur jeter le reste du vin bon marché au visage en signe de protestation.',
    'game.rpg.q3c': 'Le public garde un silence de mort. Ils pensent que votre dialecte dénonce le système.',
    'game.rpg.q3c.a': 'Aller jusqu\'au bout et mettre le feu à l\'œuvre principale.',
    'game.rpg.q3c.b': 'Rester dans un silence absolu en fixant le plafond.',
    'game.rpg.q3d': 'Vous vous échappez dans la ruelle. Vous trouvez le DJ et le traiteur en train de fumer.',
    'game.rpg.q3d.a': 'Voler les canapés, vous cacher et manger en pleurant.',
    'game.rpg.q3d.b': 'Les convaincre de monter l\'expo clandestine juste là.',
    // Endings
    'game.rpg.e1': 'FIN 1 : VENDU\nVous êtes riche. La guilde vous déteste. Vous vivez à Monaco en remettant en question votre intégrité tout en buvant du vrai champagne. Vous avez réussi (économiquement).',
    'game.rpg.e2': 'FIN 2 : MARTYR DE L\'UNDERGROUND\nLe millionnaire vous poursuit en justice. Vous êtes pauvre, mais la critique vous adore. Vous devenez une légende indomptable dans les bars sombres de la ville.',
    'game.rpg.e3': 'FIN 3 : BUREAUCRATE CULTUREL\nVous êtes massivement annulé sur Twitter. En échange, le gouvernement sponsorise vos galeries à vie. Vous avez tué votre âme, mais vous payez votre loyer à temps.',
    'game.rpg.e4': 'FIN 4 : PERFORMANCE CARCÉRALE\nVous passez la nuit en cellule. Étonnamment, le lendemain, les magazines déclarent qu\'il s\'agissait d\'une "intervention perturbatrice". Vous êtes un génie intouchable.',
    'game.rpg.e5': 'FIN 5 : ART ÉPHÉMÈRE TOTAL\nLe musée est réduit en cendres. L\'assurance ne couvre pas les "performances". Vous vous retrouvez endetté à vie mais avec l\'anecdote la plus incroyable du siècle.',
    'game.rpg.e6': 'FIN 6 : MÉMÉ HUMAIN\nVous êtes filmé sur TikTok en train de fixer le plafond. Vous devenez le mème du mois. Les banques vous recherchent pour des pubs. Vous perdez votre prestige mais gagnez des likes échangeables contre de l\'anxiété.',
    'game.rpg.e7': 'FIN 7 : SANS GLUTEN\nL\'expo échoue sans vous. Le galeriste vous renvoie. Mais vous avez découvert que les canapés au saumon étaient délicieux. Triomphe personnel.',
    'game.rpg.e8': 'FIN 8 : CONTRE-CULTURE DE RUELLE\nLa ruelle devient le nouveau happening historique. Vous détruisez l\'élitisme du cube blanc. Vous lancez un mouvement qui sera étudié dans les livres.',

    // Games - General
    'game.objective': 'Objectif : ',
    'game.retry': 'RÉESSAYER',
    'game.insert': 'INSÉRER PIÈCE',

    // Game: Pong
    'game.pong.thesis': 'Thèse (Vous)',
    'game.pong.antithesis': 'Antithèse (Algorithme)',
    'game.pong.win': 'VOUS AVEZ GAGNÉ LE DÉBAT !',
    'game.pong.lose': 'LA MACHINE VOUS A RÉFUTÉ',
    'game.pong.title': 'PONG DE DÉBAT',
    'game.pong.goal': 'Atteindre 5 points',
    'game.pong.controls': 'Utilisez la souris ou le doigt pour déplacer votre argument',

    // Game: TicTacToe
    'game.ttt.goal': '3 idées alignées',
    'game.ttt.win': 'Hégémonie de la {{winner}} !',
    'game.ttt.reason': 'Raison (X)',
    'game.ttt.tradition': 'Tradition (O)',
    'game.ttt.draw': 'Aporie : Égalité irrésoluble.',
    'game.ttt.turn': 'Tour : ',
    'game.ttt.you': 'Vous (X)',
    'game.ttt.bot': 'Machine Dogmatique (O)',
    'game.ttt.reset': 'DÉCONSTRUIRE LE SYSTÈME',
    'game.ttt.log.start': 'Le débat commence. Choisissez une prémisse.',
    'game.ttt.log.reset': 'Nouvelle tabula rasa. Le débat commence.',

    // Game: Political Uno
    'game.uno.goal': 'Épuisez vos cartes pour gagner l\'élection',
    'game.uno.msg.start': 'La chambre est en session.',
    'game.uno.msg.turn': 'Législateur, c\'est votre tour. Jouez par couleur ou idéologie.',
    'game.uno.msg.moche.win': 'Vous avez appliqué un Moche (pot-de-vin). Amende de 2 cartes !',
    'game.uno.msg.moche.lose': 'On vous a appliqué un Moche. Amende de 2 cartes !',
    'game.uno.msg.fuero.win': 'Vous avez activé le Fuero (immunité). Passez un tour.',
    'game.uno.msg.fuero.lose': 'Le rival a le Fuero. Passez un tour.',
    'game.uno.msg.alliance': 'Alliance partisane ! Change le flux politique.',
    'game.uno.msg.win': 'Vous avez gagné les élections et avez une majorité absolue !',
    'game.uno.msg.lose': 'Le système vous a vaincu. Vous êtes dans l\'opposition proportionnelle.',
    'game.uno.msg.error': 'Objection : Conflit d\'intérêts. Jouez une autre couleur/symbole.',
    'game.uno.msg.draw': 'Vous avez volé dans le budget. Intervention de l\'opposition...',
    'game.uno.msg.opposition': 'Le bloc d\'opposition prépare son vote...',
    'game.uno.msg.cpu_play': 'L\'opposition a voté. À votre tour.',
    'game.uno.msg.cpu_draw': 'L\'opposition a détourné des ressources (pioché une carte). À votre tour.',
    'game.uno.label.draw': 'PIOCHER',
    'game.uno.label.deck': 'Trésor',
    'game.uno.label.pile': 'Siège',
    'game.uno.label.hand': 'Vos Initiatives',
    'game.uno.label.reset': 'NOUVELLE LÉGISLATURE',
    'game.uno.action.moche': 'Pot-de-vin',
    'game.uno.action.fuero': 'Immunité',
    'game.uno.action.alliance': 'Inverse',

    // Game: FestJump
    'game.fest.back': 'Retour à l\'accueil',
    'game.fest.desc': 'Prototype de gamification jouable pour les festivals. Retient l\'attention des utilisateurs, délivre des codes promotionnels par étapes de distance et convertit l\'engagement en achats (billets ou merch).',
    'game.fest.title': 'Altitude',
    'game.fest.codes': 'Codes',
    'game.fest.hint': 'Montez à 500m+',
    'game.fest.objective': 'Déplacez la souris ou le doigt. Montez pour débloquer des réductions pour le festival 2026.',
    'game.fest.over': 'Game Over. Altitude : {{score}}m',
    'game.fest.discount5': 'FEST2026 (Réduction 5%)',
    'game.fest.discount10': 'BEATS26 (Réduction 10%)',
    'game.fest.discountVIP': 'VIPFEST (Accès/Boisson)'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('es');

  const t = (key: string, variables?: Record<string, string>) => {
    let text = translations[language]?.[key] || translations['es'][key] || key;
    if (variables) {
      for (const [v, val] of Object.entries(variables)) {
        text = text.replace(`{{${v}}}`, val);
      }
    }
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
