import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'es' | 'en' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, variables?: Record<string, string>) => string;
}

const translations: Record<Language, Record<string, string>> = {
  es: {
    // Nav & Common
    'nav.home': 'Inicio',
    
    // Hero
    'hero.title1': 'Catálogo',
    'hero.title2': 'Humano',
    'hero.job': 'Estratega, gestor cultural y arquitecto de experiencias.',
    'hero.desc': 'Bienvenido a mi red neuronal: un espacio interactivo donde la música, el código, y el pensamiento crítico colisionan para hackear la monotonía de la realidad.',
    'hero.inventory': 'Inventario',
    'hero.services': 'Servicios (Stats)',
    'hero.years': 'Años',
    
    // Home / Oracle Banner
    'home.testerTitle': 'Beta Tester Interactivo',
    'home.oracleTitle1': 'Oráculo de ',
    'home.oracleTitle2': 'Producción',
    'home.oracleDesc': 'Pon a prueba la viabilidad de tu idea (y mi paciencia) con el generador irónico de proyectos.',
    'home.rollDice': 'Tirar los dados',

    // Ecosystem
    'eco.label': '01 // Ecosistema',
    'eco.title': '01 // Ecosistema',
    'eco.multiverse': 'Multiverso',
    'eco.creative': '—Creativo',
    'eco.desc': 'Cada proyecto es una sinapsis. Un archivo abierto donde cruzo disciplinas para generar cortocircuitos en el pensamiento lineal y esquivar al algoritmo.',
    'eco.cat1': 'Contenido',
    'eco.proj1.desc': 'Espacio dedicado a la creación diaria de contenido cultural y filosófico. Reflexiones sobre la vida que no piden permiso.',
    'eco.proj1.link': 'Explorar Contenido',
    'eco.cat2': 'Blog & Pensamiento',
    'eco.proj2.desc': 'Mi blog personal. Pensamientos extendidos, la vida como RPG, el alma como flujo y ensayos misceláneos sobre el cansancio y el arte.',
    'eco.proj2.link': 'Leer Blog',
    'eco.cat3': 'Música',
    'eco.proj3.desc': 'Integración sonora experiencial. Composiciones que exploran los vínculos, la soledad y la vida en una época descartable.',
    'eco.proj3.link': 'Escuchar en Spotify',
    'eco.cat4': 'Arcade & Game Design',
    'eco.proj4.desc': 'Diseño y mecánicas jugables enfocadas en repensar el \'Dungeon Master\' algorítmico y político. Pong de debate y más.',
    'eco.proj4.link': 'Insert Coin',
    'eco.cat5': 'Mockup Interactivo',
    'eco.proj5.title': 'Una idea para tu evento',
    'eco.proj5.desc': 'La gamificación retiene atención donde el marketing tradicional falla. Prototipo hiper-casual asíncrono para festivales masivos. Convierte el engagement digital en compras (tickets o merch).',
    'eco.proj5.link': 'Juega la Maqueta',

    // Services
    'serv.title': '02 // Inventario de Habilidades',
    'serv.tree': 'Árbol de',
    'serv.skills': 'Skills',
    'serv.desc': 'El backend de mi ecosistema. Herramientas de despliegue táctico donde transfiero la teoría abstracta a resultados operativos y tangibles.',
    'serv.s1.title': 'Estrategia y Megaproducción',
    'serv.s1.desc': 'Traducir visión en logística impecable. De albergar exposiciones internacionales para gobiernos locales e IP, y dirigir subastas de arte de alto impacto social, hasta levantar festivales masivos desde la conceptualización de la idea hasta el evento.',
    'serv.s2.title': 'Política Cultural & Impacto Social',
    'serv.s2.desc': 'Especialista en reactivación comunitaria. He diseñado programas socioculturales (STEAM) tejiendo alianzas globales y locales, logrando resultados tangibles en el territorio a partir de un pensamiento táctico.',
    'serv.s3.title': 'Pensamiento, Narrativa & Oratoria',
    'serv.s3.desc': 'Maestría en Gestión Cultural, Filosofía por la BUAP y Vanguardias en la U. de Salamanca. Diseño discursos, guiones y textos institucionales o literarios que capturan la atención respetando la inteligencia del lector.',
    'serv.s4.title': 'Código, Interfaz y Subversión Web',
    'serv.s4.desc': 'El software es la infraestructura del presente. Construyo ecosistemas web a medida y mecánicas gamificadas para instituciones o creadores que buscan formatos distintos a la plantilla corporativa.',

    // Manifesto
    'mani.title': '03 // Manifiesto',
    'mani.h3': 'Sísifo,',
    'mani.h3.sub': 'pero con un HUD customizado.',
    'mani.quote': '"Soy un filósofo que aprendió a cuadrar presupuestos en Excel, o un productor infiltrado en la academia."',
    'mani.p1': 'Mi bitácora no es una línea recta, es un mapa de colisiones. Pasé por Filosofía en la BUAP, Vanguardias Estéticas en la Universidad de Salamanca (cruzando Madrid) y culminé con una Maestría en Gestión Cultural. Opero desde MX no sólo para observar, sino para detonar intelecto y energía creativa a escala masiva.',
    'mani.p2_1': 'En mi red convergen agendas interinstitucionales con decenas de embajadas, subastas de impacto social y estrategias de inversión privada. He llevado estas visiones del papel al músculo operativo: coordinando ',
    'mani.p2_2': 'más de 600 eventos',
    'mani.p2_3': ', logrando ',
    'mani.p2_4': '+500,000 impactos directos',
    'mani.p2_5': ' y extendiendo estos ecosistemas a ',
    'mani.p2_6': '10 países',
    'mani.p2_7': '.',
    'mani.p3': 'Conozco de primera mano la sobreestimulación contemporánea; por eso creo mis propias salidas de emergencia. Programar una plataforma interactiva o diseñar un macro-festival exige la misma precisión técnica: ordenar el caos e inyectar sentido humano justo allí donde el algoritmo exige ruido.',
    'mani.box1.title': 'Input Neuronal',
    'mani.box1.desc': 'Filosofía / Vanguardias / Diseño',
    'mani.box2.title': 'Procesamiento',
    'mani.box2.desc': '+600 Eventos / Gestión Dinámica',
    'mani.box3.title': 'Output Desplegado',
    'mani.box3.desc': '+500k Impactos en 10 Países',

    // Footer
    'footer.title.main': '¿Hablamos de negocios,',
    'footer.title.sub': 'o de la {{highlight}} del mundo?',
    'footer.title.highlight': 'ruina',
    'footer.direct': 'Formulario Directo',
    'footer.online': '[ En línea ]',
    'footer.send': 'Enviar Transmisión',
    'footer.rights': 'Todos los derechos reservados.',
    'footer.made': 'Hecho con frustración al capitalismo, y código.',
    'footer.comms': 'Comms_',
    'footer.base': 'Base_',
    'footer.net': 'Red_',
    'footer.subtitle': 'Para contrataciones de servicios web, conferencias, colaboraciones musicales o debates filosóficos a las 3 AM.',
    'footer.links.comms': 'Transmisión & Base',
    'footer.links.net': 'Redes & Ecosistema',
    'footer.form.name.label': 'Nombre / Entidad',
    'footer.form.name.ph': 'Escribe tu identidad...',
    'footer.form.email.label': 'Correo Electrónico',
    'footer.form.email.ph': 'correo@ejemplo.com',
    'footer.form.subject': 'Contacto desde Catálogo Humano',
    'footer.form.topic.label': 'Motivo del Encuentro',
    'footer.form.topic.opt1': 'Selecciona un motivo...',
    'footer.form.topic.opt2': 'Servicios Web',
    'footer.form.topic.opt3': 'Juegos Web',
    'footer.form.topic.opt4': 'Gestión Cultural & Conferencias',
    'footer.form.topic.opt5': 'Colaboración Musical',
    'footer.form.topic.opt6': 'Otros asuntos (quejas existenciales)',
    'footer.form.msg.label': 'Mensaje',
    'footer.form.msg.ph': 'Detalla tu idea o crisis...',

    // Oracle Page
    'orc.back': '[ Base Central ]',
    'orc.badge': 'Oráculo de Producción',
    'orc.title1': 'Dime qué quieres',
    'orc.title2': 'y te diré la verdad.',
    'orc.desc': '¿Tienes un evento en mente? El algoritmo evalúa su viabilidad (con una dosis severa de escepticismo). Ponle nombre, tira los dados y veamos a qué nos enfrentamos.',
    'orc.input.label': 'Inyecta el nombre del proyecto:',
    'orc.input.placeholder': 'Ej. Cyberpunk Fest...',
    'orc.btn.spin': 'Tirar los dados del destino',
    'orc.diag': 'Diagnóstico de Realidad Generado',
    'orc.lbl1': 'Formato Cortocircuito',
    'orc.lbl2': 'Sede Temeraria',
    'orc.lbl3': 'Público Involuntario',
    'orc.lbl4': 'Capital Disponible',
    'orc.btn.action': 'Sacar del Pizarrón',
    'orc.btn.reset': '[ Re-calcular ]',

    // Arcade
    'arc.back': '[ Base Central ]',
    'arc.restricted': 'ARCHIVOS RESTRINGIDOS',
    'arc.sisyphus': '—Sísifo',
    'arc.desc': 'Porque la vida es un RPG roto sin manual. Desconecta de la hiperproductividad y ríete del algoritmo.',
    'arc.game1': 'Pong de Debate',
    'arc.game2': 'Cartas Políticas',
    'arc.game3': 'Gato de Ideas',

    // Games - General
    'game.objective': 'Objetivo: ',
    'game.retry': 'REINTENTAR',
    'game.insert': 'INSERT COIN',

    // Game: Pong
    'game.pong.thesis': 'Tesis (Tú)',
    'game.pong.antithesis': 'Antítesis (Algoritmo)',
    'game.pong.win': '¡GANASTE EL DEBATE!',
    'game.pong.lose': 'LA MÁQUINA TE REFUTÓ',
    'game.pong.title': 'PONG DE DEBATE',
    'game.pong.goal': 'Llega a 5 puntos',
    'game.pong.controls': 'Usa el ratón o dedo para mover tu argumento',

    // Game: TicTacToe
    'game.ttt.goal': '3 ideas alineadas',
    'game.ttt.win': '¡Hegemonía de la {{winner}}!',
    'game.ttt.reason': 'Razón (X)',
    'game.ttt.tradition': 'Tradición (O)',
    'game.ttt.draw': 'Aporía: Empate irresoluble.',
    'game.ttt.turn': 'Turno: ',
    'game.ttt.you': 'Tú (X)',
    'game.ttt.bot': 'Máquina Dogmática (O)',
    'game.ttt.reset': 'DECONSTRUIR SISTEMA',
    'game.ttt.log.start': 'El debate comienza. Elige una premisa.',
    'game.ttt.log.reset': 'Nueva tabula rasa. Comienza el debate.',

    // Game: Political Uno
    'game.uno.goal': 'Quédate sin cartas para ganar la elección',
    'game.uno.msg.start': 'La cámara está en sesión.',
    'game.uno.msg.turn': 'Legislador, es tu turno. Juega por color o ideología.',
    'game.uno.msg.moche.win': 'Aplicaste un Moche. ¡Multa de 2 cartas!',
    'game.uno.msg.moche.lose': 'Te aplicaron un Moche. ¡Multa de 2 cartas!',
    'game.uno.msg.fuero.win': 'Activaste Fuero. Se salta un turno.',
    'game.uno.msg.fuero.lose': 'El rival tiene Fuero. Se salta un turno.',
    'game.uno.msg.alliance': '¡Alianza partidista! Cambia el flujo político.',
    'game.uno.msg.win': '¡Ganaste las elecciones y tienes mayoría absoluta!',
    'game.uno.msg.lose': 'El sistema te ha vencido. Eres oposición plurinominal.',
    'game.uno.msg.error': 'Objeción: Conflicto de interés. Juega otro color/símbolo.',
    'game.uno.msg.draw': 'Robaste presupuesto. Intervención de la oposición...',
    'game.uno.msg.opposition': 'El bloque opositor está maquinando su voto...',
    'game.uno.msg.cpu_play': 'La oposición ha votado. Tu turno.',
    'game.uno.msg.cpu_draw': 'La oposición desvió recursos (robó carta). Tu turno.',
    'game.uno.label.draw': 'ROBAR',
    'game.uno.label.deck': 'Erario',
    'game.uno.label.pile': 'Curul',
    'game.uno.label.hand': 'Tus Iniciativas',
    'game.uno.label.reset': 'NUEVA LEGISLATURA',
    'game.uno.action.moche': 'Moche',
    'game.uno.action.fuero': 'Fuero',
    'game.uno.action.alliance': 'Reversa',

    // Game: FestJump
    'game.fest.back': 'Volver al Inicio',
    'game.fest.desc': 'Prototipo jugable de gamificación para festivales. Retiene atención de usuarios, entrega códigos promocionales por hitos de distancia, y convierte el engagement en compras (tickets o merch).',
    'game.fest.title': 'Altitud',
    'game.fest.codes': 'Códigos',
    'game.fest.hint': 'Sube 500m+',
    'game.fest.objective': 'Mueve el ratón o el dedo. Sube para desbloquear descuentos para el festival 2026.',
    'game.fest.over': 'Game Over. Altura: {{score}}m',
    'game.fest.discount5': 'FEST2026 (5% Descuento)',
    'game.fest.discount10': 'BEATS26 (10% Descuento)',
    'game.fest.discountVIP': 'VIPFEST (Acces/Bebida)'
  },
  en: {
    'nav.home': 'Home',
    // Hero
    'hero.title1': 'Human',
    'hero.title2': 'Catalog',
    'hero.job': 'Strategist, cultural manager and experience architect.',
    'hero.desc': 'Welcome to my neural network: an interactive space where music, code, and critical thinking collide to hack the monotony of reality.',
    'hero.inventory': 'Inventory',
    'hero.services': 'Services (Stats)',
    'hero.years': 'Years',

    'home.testerTitle': 'Interactive Beta Tester',
    'home.oracleTitle1': 'Production ',
    'home.oracleTitle2': 'Oracle',
    'home.oracleDesc': 'Test the viability of your idea (and my patience) with this ironic project generator.',
    'home.rollDice': 'Roll the Dice',

    'eco.label': '01 // Ecosystem',
    'eco.title': '01 // Ecosystem',
    'eco.multiverse': 'Creative',
    'eco.creative': '—Multiverse',
    'eco.desc': 'Every project is a synapse. An open file where I cross disciplines to generate short circuits in linear thinking and dodge the algorithm.',
    'eco.cat1': 'Content',
    'eco.proj1.desc': 'Space dedicated to the daily creation of cultural and philosophical content. Reflections on life that do not ask for permission.',
    'eco.proj1.link': 'Explore Content',
    'eco.cat2': 'Blog & Thought',
    'eco.proj2.desc': 'My personal blog. Extended thoughts, life as an RPG, the soul as a flow and miscellaneous essays on exhaustion and art.',
    'eco.proj2.link': 'Read Blog',
    'eco.cat3': 'Music',
    'eco.proj3.desc': 'Experiential sonic integration. Compositions that explore bonds, loneliness and life in a disposable era.',
    'eco.proj3.link': 'Listen on Spotify',
    'eco.cat4': 'Arcade & Game Design',
    'eco.proj4.desc': 'Game design and mechanics focused on rethinking the algorithmic and political \'Dungeon Master\'. Debate Pong and more.',
    'eco.proj4.link': 'Insert Coin',
    'eco.cat5': 'Interactive Mockup',
    'eco.proj5.title': 'An idea for your event',
    'eco.proj5.desc': 'Gamification retains attention where traditional marketing fails. Asynchronous hyper-casual prototype for massive festivals.',
    'eco.proj5.link': 'Play the Mockup',

    'serv.title': '02 // Skill Inventory',
    'serv.tree': 'Skill ',
    'serv.skills': 'Tree',
    'serv.desc': 'The backend of my ecosystem. Tactical deployment tools where I transfer abstract theory into operational and tangible results.',
    'serv.s1.title': 'Strategy & Mega-Production',
    'serv.s1.desc': 'Translating vision into flawless logistics. From hosting international exhibitions for local governments and IP, to raising entire festivals.',
    'serv.s2.title': 'Cultural Policy & Social Impact',
    'serv.s2.desc': 'Specialist in community reactivation. I have designed sociocultural programs (STEAM) weaving global and local alliances.',
    'serv.s3.title': 'Thought, Narrative & Public Speaking',
    'serv.s3.desc': 'Discourse design, scripts, and texts that capture attention while respecting the reader\'s intelligence.',
    'serv.s4.title': 'Code, Interface & Web Subversion',
    'serv.s4.desc': 'Software is the infrastructure of the present. I build tailor-made web ecosystems and gamified mechanics for creators.',

    'mani.title': '03 // Manifesto',
    'mani.h3': 'Sisyphus,',
    'mani.h3.sub': 'but with a customized HUD.',
    'mani.quote': '"I am a philosopher who learned to balance budgets in Excel, or a producer infiltrating academia."',
    'mani.p1': 'My logbook is not a straight line, it is a map of collisions. I studied Philosophy at BUAP, Aesthetic Avant-gardes at the University of Salamanca and finished with a Master\'s in Cultural Management. I operate from MX not just to observe, but to detonate intellect and creative energy on a massive scale.',
    'mani.p2_1': 'In my network, inter-institutional agendas converge with dozens of embassies, social impact auctions, and private investment strategies. I have taken these visions from paper to operational muscle: coordinating ',
    'mani.p2_2': 'more than 600 events',
    'mani.p2_3': ', achieving ',
    'mani.p2_4': '+500,000 direct impacts',
    'mani.p2_5': ' and extending these ecosystems to ',
    'mani.p2_6': '10 countries',
    'mani.p2_7': '.',
    'mani.p3': 'I know contemporary overstimulation firsthand; that\'s why I create my own emergency exits. Programming an interactive platform or designing a macro-festival requires the same technical precision: ordering chaos and injecting human meaning right where the algorithm demands noise.',
    'mani.box1.title': 'Neural Input',
    'mani.box1.desc': 'Philosophy / Avant-gardes / Design',
    'mani.box2.title': 'Processing',
    'mani.box2.desc': '+600 Events / Dynamic Management',
    'mani.box3.title': 'Deployed Output',
    'mani.box3.desc': '+500k Impacts in 10 Countries',

    'footer.title.main': 'Shall we talk business,',
    'footer.title.sub': 'or the {{highlight}} of the world?',
    'footer.title.highlight': 'ruin',
    'footer.direct': 'Direct Form',
    'footer.online': '[ Online ]',
    'footer.send': 'Send Transmission',
    'footer.rights': 'All rights reserved.',
    'footer.made': 'Made with frustration towards capitalism, and code.',
    'footer.comms': 'Comms_',
    'footer.base': 'Base_',
    'footer.net': 'Net_',
    'footer.subtitle': 'For web services, public speaking, musical collaborations, or philosophical debates at 3 AM.',
    'footer.links.comms': 'Transmission & Base',
    'footer.links.net': 'Network & Ecosystem',
    'footer.form.name.label': 'Name / Entity',
    'footer.form.name.ph': 'Write your identity...',
    'footer.form.email.label': 'Email Address',
    'footer.form.email.ph': 'email@example.com',
    'footer.form.subject': 'Contact from Human Catalog',
    'footer.form.topic.label': 'Reason for Encounter',
    'footer.form.topic.opt1': 'Select a reason...',
    'footer.form.topic.opt2': 'Web Services',
    'footer.form.topic.opt3': 'Web Games',
    'footer.form.topic.opt4': 'Cultural Management & Conferences',
    'footer.form.topic.opt5': 'Musical Collaboration',
    'footer.form.topic.opt6': 'Other matters (existential complaints)',
    'footer.form.msg.label': 'Message',
    'footer.form.msg.ph': 'Detail your idea or crisis...',

    'orc.back': '[ Central Base ]',
    'orc.badge': 'Production Oracle',
    'orc.title1': 'Tell me what you want',
    'orc.title2': 'and I will tell you the truth.',
    'orc.desc': 'Have an event in mind? The algorithm evaluates its viability (with a severe dose of skepticism). Name it, roll the dice, and let\'s see.',
    'orc.input.label': 'Inject project name:',
    'orc.input.placeholder': 'E.g. Cyberpunk Fest...',
    'orc.btn.spin': 'Roll the Dice of Destiny',
    'orc.diag': 'Generated Reality Diagnosis',
    'orc.lbl1': 'Short Circuit Format',
    'orc.lbl2': 'Reckless Venue',
    'orc.lbl3': 'Involuntary Audience',
    'orc.lbl4': 'Available Capital',
    'orc.btn.action': 'Take it off the Board',
    'orc.btn.reset': '[ Re-calculate ]',

    // Arcade
    'arc.back': '[ Central Base ]',
    'arc.restricted': 'RESTRICTED ARCHIVES',
    'arc.sisyphus': '—Sisyphus',
    'arc.desc': 'Because life is a broken RPG with no manual. Disconnect from hyper-productivity and laugh at the algorithm.',
    'arc.game1': 'Debate Pong',
    'arc.game2': 'Political Cards',
    'arc.game3': 'Ideas Tic-Tac-Toe',

    // Games - General
    'game.objective': 'Objective: ',
    'game.retry': 'RETRY',
    'game.insert': 'INSERT COIN',

    // Game: Pong
    'game.pong.thesis': 'Thesis (You)',
    'game.pong.antithesis': 'Antithesis (Algorithm)',
    'game.pong.win': 'YOU WON THE DEBATE!',
    'game.pong.lose': 'THE MACHINE REFUTED YOU',
    'game.pong.title': 'DEBATE PONG',
    'game.pong.goal': 'Reach 5 points',
    'game.pong.controls': 'Use mouse or finger to move your argument',

    // Game: TicTacToe
    'game.ttt.goal': '3 aligned ideas',
    'game.ttt.win': '{{winner}} Hegemony!',
    'game.ttt.reason': 'Reason (X)',
    'game.ttt.tradition': 'Tradition (O)',
    'game.ttt.draw': 'Aporia: Irresolvable draw.',
    'game.ttt.turn': 'Turn: ',
    'game.ttt.you': 'You (X)',
    'game.ttt.bot': 'Dogmatic Machine (O)',
    'game.ttt.reset': 'DECONSTRUCT SYSTEM',
    'game.ttt.log.start': 'The debate begins. Choose a premise.',
    'game.ttt.log.reset': 'New tabula rasa. The debate begins.',

    // Game: Political Uno
    'game.uno.goal': 'Run out of cards to win the election',
    'game.uno.msg.start': 'The chamber is in session.',
    'game.uno.msg.turn': 'Legislator, it is your turn. Play by color or ideology.',
    'game.uno.msg.moche.win': 'You applied a Moche (bribe). 2-card fine!',
    'game.uno.msg.moche.lose': 'They applied a Moche to you. 2-card fine!',
    'game.uno.msg.fuero.win': 'You activated Fuero (immunity). Skip a turn.',
    'game.uno.msg.fuero.lose': 'The rival has Fuero. Skip a turn.',
    'game.uno.msg.alliance': 'Partisan alliance! Changes the political flow.',
    'game.uno.msg.win': 'You won the elections and have an absolute majority!',
    'game.uno.msg.lose': 'The system has defeated you. You are in the proportional opposition.',
    'game.uno.msg.error': 'Objection: Conflict of interest. Play another color/symbol.',
    'game.uno.msg.draw': 'You stole from the budget. Opposition intervention...',
    'game.uno.msg.opposition': 'The opposition block is plotting their vote...',
    'game.uno.msg.cpu_play': 'The opposition has voted. Your turn.',
    'game.uno.msg.cpu_draw': 'The opposition diverted resources (drew a card). Your turn.',
    'game.uno.label.draw': 'DRAW',
    'game.uno.label.deck': 'Treasury',
    'game.uno.label.pile': 'Seat',
    'game.uno.label.hand': 'Your Initiatives',
    'game.uno.label.reset': 'NEW LEGISLATURE',
    'game.uno.action.moche': 'Bribe',
    'game.uno.action.fuero': 'Immunity',
    'game.uno.action.alliance': 'Reverse',

    // Game: FestJump
    'game.fest.back': 'Back to Home',
    'game.fest.desc': 'Playable gamification prototype for festivals. Retains user attention, delivers promo codes for distance milestones, and converts engagement into purchases (tickets or merch).',
    'game.fest.title': 'Altitude',
    'game.fest.codes': 'Codes',
    'game.fest.hint': 'Climb 500m+',
    'game.fest.objective': 'Move the mouse or finger. Climb to unlock discounts for the 2026 festival.',
    'game.fest.over': 'Game Over. Altitude: {{score}}m',
    'game.fest.discount5': 'FEST2026 (5% Discount)',
    'game.fest.discount10': 'BEATS26 (10% Discount)',
    'game.fest.discountVIP': 'VIPFEST (Access/Drink)'
  },
  fr: {
    'nav.home': 'Accueil',
    // Hero
    'hero.title1': 'Catalogue',
    'hero.title2': 'Humain',
    'hero.job': 'Stratège, gestionnaire culturel et architecte d\'expériences.',
    'hero.desc': 'Bienvenue dans mon réseau de neurones : un espace interactif où la musique, le code et la pensée critique s\'entrechoquent pour pirater la monotonie de la réalité.',
    'hero.inventory': 'Inventaire',
    'hero.services': 'Services (Stats)',
    'hero.years': 'Ans',

    'home.testerTitle': 'Bêta Testeur Interactif',
    'home.oracleTitle1': 'Oracle de ',
    'home.oracleTitle2': 'Production',
    'home.oracleDesc': 'Testez la viabilité de votre idée (et ma patience) avec ce générateur de projet ironique.',
    'home.rollDice': 'Lancer les dés',

    'eco.label': '01 // Écosystème',
    'eco.title': '01 // Écosystème',
    'eco.multiverse': 'Créatif',
    'eco.creative': '—Multivers',
    'eco.desc': 'Chaque projet est une synapse. Un dossier ouvert où je croise les disciplines pour générer des courts-circuits dans la pensée linéaire et esquiver l\'algorithme.',
    'eco.cat1': 'Contenu',
    'eco.proj1.desc': 'Espace dédié à la création quotidienne de contenu culturel et philosophique. Des réflexions sur la vie.',
    'eco.proj1.link': 'Explorer le contenu',
    'eco.cat2': 'Blog & Pensée',
    'eco.proj2.desc': 'Mon blog personnel. Pensées étendues, la vie comme un RPG, des essais divers sur l\'épuisement et l\'art.',
    'eco.proj2.link': 'Lire le blog',
    'eco.cat3': 'Musique',
    'eco.proj3.desc': 'Intégration sonore expérientielle. Compositions qui explorent les liens, la solitude et la vie à une époque jetable.',
    'eco.proj3.link': 'Écouter sur Spotify',
    'eco.cat4': 'Arcade & Game Design',
    'eco.proj4.desc': 'Conception et mécanique de jeu axées sur la refonte du \'Dungeon Master\' algorithmique et politique. Debate Pong et plus.',
    'eco.proj4.link': 'Insérer une pièce',
    'eco.cat5': 'Maquette Interactive',
    'eco.proj5.title': 'Une idée pour votre événement',
    'eco.proj5.desc': 'La gamification retient l\'attention là où le marketing traditionnel échoue. Prototype hyper-casual asynchrone pour les grands festivals.',
    'eco.proj5.link': 'Jouer la maquette',

    'serv.title': '02 // Inventaire des Compétences',
    'serv.tree': 'Arbre de ',
    'serv.skills': 'Compétences',
    'serv.desc': 'Le backend de mon écosystème. Outils de déploiement tactique où je transfère la théorie abstraite en résultats opérationnels.',
    'serv.s1.title': 'Stratégie et Mégaproduction',
    'serv.s1.desc': 'Traduire la vision en logistique impeccable. De l\'hébergement d\'expositions internationales à la création de festivals massifs.',
    'serv.s2.title': 'Politique Culturelle & Impact Social',
    'serv.s2.desc': 'Spécialiste en réactivation communautaire. J\'ai conçu des programmes socioculturels (STEAM) tissant des alliances globales et locales.',
    'serv.s3.title': 'Pensée, Récit & Art Oratoire',
    'serv.s3.desc': 'Conception de discours, scénarios et textes qui captent l\'attention tout en respectant l\'intelligence du lecteur.',
    'serv.s4.title': 'Code, Interface et Subversion Web',
    'serv.s4.desc': 'Je construis des écosystèmes web sur mesure et des mécaniques gamifiées pour les créateurs qui recherchent des formats uniques.',

    'mani.title': '03 // Manifeste',
    'mani.h3': 'Sisyphe,',
    'mani.h3.sub': 'mais avec un HUD personnalisé.',
    'mani.quote': '"Je suis un philosophe qui a appris à équilibrer des budgets sur Excel, ou un producteur infiltré dans le milieu universitaire."',
    'mani.p1': 'Mon journal de bord n\'est pas une ligne droite, c\'est une carte de collisions. J\'ai étudié la philosophie à la BUAP, les avant-gardes esthétiques à l\'Université de Salamanque et j\'ai terminé par une maîtrise en gestion culturelle. J\'opère depuis MX non seulement pour observer, mais pour faire exploser l\'intellect et l\'énergie créative à grande échelle.',
    'mani.p2_1': 'Dans mon réseau convergent des agendas interinstitutionnels avec des dizaines d\'ambassades, des ventes aux enchères à impact social et des stratégies d\'investissement privé. J\'ai fait passer ces visions du papier au muscle opérationnel : en coordonnant ',
    'mani.p2_2': 'plus de 600 événements',
    'mani.p2_3': ', en obtenant ',
    'mani.p2_4': '+500 000 impacts directs',
    'mani.p2_5': ' et en étendant ces écosystèmes à ',
    'mani.p2_6': '10 pays',
    'mani.p2_7': '.',
    'mani.p3': 'Je connais la surstimulation contemporaine de première main ; c\'est pourquoi je crée mes propres sorties de secours. Programmer une plateforme interactive ou concevoir un macro-festival exige la même précision technique : ordonner le chaos et injecter du sens humain là où l\'algorithme exige du bruit.',
    'mani.box1.title': 'Entrée Neurale',
    'mani.box1.desc': 'Philosophie / Avant-gardes / Design',
    'mani.box2.title': 'Traitement',
    'mani.box2.desc': '+600 Événements / Gestion Dynamique',
    'mani.box3.title': 'Sortie Déployée',
    'mani.box3.desc': '+500k Impacts dans 10 Pays',

    'footer.title.main': 'Parlons-nous affaires,',
    'footer.title.sub': 'ou de la {{highlight}} du monde ?',
    'footer.title.highlight': 'ruine',
    'footer.direct': 'Formulaire Direct',
    'footer.online': '[ En ligne ]',
    'footer.send': 'Envoyer la Transmission',
    'footer.rights': 'Tous droits réservés.',
    'footer.made': 'Fait avec frustration envers le capitalisme, et du code.',
    'footer.comms': 'Comms_',
    'footer.base': 'Base_',
    'footer.net': 'Net_',
    'footer.subtitle': 'Pour des services web, des conférences, des collaborations musicales ou des débats philosophiques à 3h du matin.',
    'footer.links.comms': 'Transmission & Base',
    'footer.links.net': 'Réseaux & Écosystème',
    'footer.form.name.label': 'Nom / Entité',
    'footer.form.name.ph': 'Écrivez votre identité...',
    'footer.form.email.label': 'Adresse E-mail',
    'footer.form.email.ph': 'email@exemple.com',
    'footer.form.subject': 'Contact depuis le Catalogue Humain',
    'footer.form.topic.label': 'Motif de la Rencontre',
    'footer.form.topic.opt1': 'Sélectionnez un motif...',
    'footer.form.topic.opt2': 'Services Web',
    'footer.form.topic.opt3': 'Jeux Web',
    'footer.form.topic.opt4': 'Gestion Culturelle & Conférences',
    'footer.form.topic.opt5': 'Collaboration Musicale',
    'footer.form.topic.opt6': 'Autres affaires (plaintes existentielles)',
    'footer.form.msg.label': 'Message',
    'footer.form.msg.ph': 'Détaillez votre idée ou crise...',

    'orc.back': '[ Base Centrale ]',
    'orc.badge': 'Oracle de Production',
    'orc.title1': 'Dis-moi ce que tu veux',
    'orc.title2': 'et je te dirai la vérité.',
    'orc.desc': 'Vous avez un événement en tête? L\'algorithme évalue sa viabilité. Nommez-le, lancez les dés, et voyons.',
    'orc.input.label': 'Injecter le nom du projet:',
    'orc.input.placeholder': 'Ex. Cyberpunk Fest...',
    'orc.btn.spin': 'Lancer les dés du destin',
    'orc.diag': 'Diagnostic de Réalité Généré',
    'orc.lbl1': 'Format Court-circuit',
    'orc.lbl2': 'Lieu Imprudent',
    'orc.lbl3': 'Public Involontaire',
    'orc.lbl4': 'Capital Disponible',
    'orc.btn.action': 'Prenez-le du tableau',
    'orc.btn.reset': '[ Re-calculer ]',

    // Arcade
    'arc.back': '[ Base Centrale ]',
    'arc.restricted': 'ARCHIVES RESTREINTES',
    'arc.sisyphus': '—Sisyphe',
    'arc.desc': 'Parce que la vie est un RPG cassé sans manuel. Déconnectez-vous de l\'hyperproductivité et riez de l\'algorithme.',
    'arc.game1': 'Pong de Débat',
    'arc.game2': 'Cartes Politiques',
    'arc.game3': 'Morpion d\'Idées',

    // Games - General
    'game.objective': 'Objectif : ',
    'game.retry': 'RÉESSAYER',
    'game.insert': 'INSÉRER PIÈCE',

    // Game: Pong
    'game.pong.thesis': 'Thèse (Vous)',
    'game.pong.antithesis': 'Antithèse (Algorithme)',
    'game.pong.win': 'VOUS AVEZ GAGNÉ LE DÉBAT !',
    'game.pong.lose': 'LA MACHINE VOUS A RÉFUTÉ',
    'game.pong.title': 'PONG DE DÉBAT',
    'game.pong.goal': 'Atteindre 5 points',
    'game.pong.controls': 'Utilisez la souris ou le doigt pour déplacer votre argument',

    // Game: TicTacToe
    'game.ttt.goal': '3 idées alignées',
    'game.ttt.win': 'Hégémonie de la {{winner}} !',
    'game.ttt.reason': 'Raison (X)',
    'game.ttt.tradition': 'Tradition (O)',
    'game.ttt.draw': 'Aporie : Égalité irrésoluble.',
    'game.ttt.turn': 'Tour : ',
    'game.ttt.you': 'Vous (X)',
    'game.ttt.bot': 'Machine Dogmatique (O)',
    'game.ttt.reset': 'DÉCONSTRUIRE LE SYSTÈME',
    'game.ttt.log.start': 'Le débat commence. Choisissez une prémisse.',
    'game.ttt.log.reset': 'Nouvelle tabula rasa. Le débat commence.',

    // Game: Political Uno
    'game.uno.goal': 'Épuisez vos cartes pour gagner l\'élection',
    'game.uno.msg.start': 'La chambre est en session.',
    'game.uno.msg.turn': 'Législateur, c\'est votre tour. Jouez par couleur ou idéologie.',
    'game.uno.msg.moche.win': 'Vous avez appliqué un Moche (pot-de-vin). Amende de 2 cartes !',
    'game.uno.msg.moche.lose': 'On vous a appliqué un Moche. Amende de 2 cartes !',
    'game.uno.msg.fuero.win': 'Vous avez activé le Fuero (immunité). Passez un tour.',
    'game.uno.msg.fuero.lose': 'Le rival a le Fuero. Passez un tour.',
    'game.uno.msg.alliance': 'Alliance partisane ! Change le flux politique.',
    'game.uno.msg.win': 'Vous avez gagné les élections et avez une majorité absolue !',
    'game.uno.msg.lose': 'Le système vous a vaincu. Vous êtes dans l\'opposition proportionnelle.',
    'game.uno.msg.error': 'Objection : Conflit d\'intérêts. Jouez une autre couleur/symbole.',
    'game.uno.msg.draw': 'Vous avez volé dans le budget. Intervention de l\'opposition...',
    'game.uno.msg.opposition': 'Le bloc d\'opposition prépare son vote...',
    'game.uno.msg.cpu_play': 'L\'opposition a voté. À votre tour.',
    'game.uno.msg.cpu_draw': 'L\'opposition a détourné des ressources (pioché une carte). À votre tour.',
    'game.uno.label.draw': 'PIOCHER',
    'game.uno.label.deck': 'Trésor',
    'game.uno.label.pile': 'Siège',
    'game.uno.label.hand': 'Vos Initiatives',
    'game.uno.label.reset': 'NOUVELLE LÉGISLATURE',
    'game.uno.action.moche': 'Pot-de-vin',
    'game.uno.action.fuero': 'Immunité',
    'game.uno.action.alliance': 'Inverse',

    // Game: FestJump
    'game.fest.back': 'Retour à l\'accueil',
    'game.fest.desc': 'Prototype de gamification jouable pour les festivals. Retient l\'attention des utilisateurs, délivre des codes promotionnels par étapes de distance et convertit l\'engagement en achats (billets ou merch).',
    'game.fest.title': 'Altitude',
    'game.fest.codes': 'Codes',
    'game.fest.hint': 'Montez à 500m+',
    'game.fest.objective': 'Déplacez la souris ou le doigt. Montez pour débloquer des réductions pour le festival 2026.',
    'game.fest.over': 'Game Over. Altitude : {{score}}m',
    'game.fest.discount5': 'FEST2026 (Réduction 5%)',
    'game.fest.discount10': 'BEATS26 (Réduction 10%)',
    'game.fest.discountVIP': 'VIPFEST (Accès/Boisson)'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('es');

  const t = (key: string, variables?: Record<string, string>) => {
    let text = translations[language]?.[key] || translations['es'][key] || key;
    if (variables) {
      for (const [v, val] of Object.entries(variables)) {
        text = text.replace(`{{${v}}}`, val);
      }
    }
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
